itoa_test : itoa.cpp
	g++ itoa.cpp -o itoa_test
strcpy : strcpy.cpp strcpy_test.cpp
	g++ strcpy.cpp strcpy_test.cpp -o strcpy
strcat : strcat.cpp strcat_test.cpp
	g++ strcat.cpp strcat_test.cpp -o strcat
left_rotation: left_rotation.cpp left_rotation_test.cpp
	g++ left_rotation.cpp left_rotation_test.cpp -o left_rotation
